### ISSUE TITLE
[Feature Request] Add command to clear active Bad Omen effect from all players in the world

### ISSUE THREAD

**Issue by MCHalfAssed** [jpenilla/AntiRaidFarm#8]
Hello!

Would you be able to add a command that would clear Bad Omen effect from all players in the world? Something like '/arfclear badomen' (I know a terrible name, sorry lol)

Reason for this: If a player has bypass, and is using a raid farm, and then I remove bypass - They can still keep using the raidfarm until bad omen runs out. If I had a command to clear bad omen from all players, then would stop all the farms immediately. 

It would be helpful to have this added to your plugin rather than needing to make one. :)

**Comment by jpenilla** [comment]
I think `/effect clear @a[nbt={Dimension:"dimension:key"}] bad_omen` should do the trick?
Not completely against adding a command for convenience, but you can do this with vanilla commands.

**Comment by MCHalfAssed** [comment]
Thanks for the swift response!

Your command didn't work, but I shortened it to: /effect clear @a minecraft:bad_omen

and it worked!

Thank you so much for the tip. If you'd like you can close this ticket, or you can add this command to your plugin since I think it applies to the purpose of disabling raid farms swiftly. :)
